#!/bin/bash

#version="$Id: delete_rels.sh,v 1.1 2011/01/10 17:00:38 ekorhor Exp $"

# ___ Help _____________________________________________________________________

if [ $# -ne 2 ] || ! ( [ "xINT" == "x$1" ] || [ "xEXT" == "x$1" ] || [ "xUTRAN" == "x$1" ] )
then
    This=`echo $0 | sed "s/^.*\///g"`
cat<<__END_OF_HELP__
Usage: $This <RelationType> <BSCRelsFile>

where
 RelationType
  - 'INT': delete internal GSM realtions
  - 'EXT': delete external GSM realtions
  - 'UTRAN': delete external UTRAN realtions
 BSCRelsFile
    The CSV file of orignal list of relations in a BSC ne between internal GSM
    and internal/external GSM or external UTRAN cells.
    The relations file must be generated by list_BSC_rels.sh script. For file
    format informations see that.

Example:
 $This EXT BSC01.BSCRels

DESCRIPTION:
 Generate MML scripts from relation list that delete the specified type of
 realtions from the BSC node.

__END_OF_HELP__
exit 1
fi


# ___ Parameters _______________________________________________________________

# Parameters
RelationType=$1
RelsPath=$2


# ___ Main activity ____________________________________________________________

echo ".asyncmsgwait ensurestartedandreset"
echo ""
# OLD: this code delete all relations
# grep -v "^[ ]*$" $RelsPath | grep -v "^[ ]*#" | cut -d , -f 4-6 |
#     sed "s/CELL=//g" | sed "s/CELLR=//g" | sed "s/DIR=//g" |
#     awk -F , '{if("SINGLE"==$3 || $1<$2) {printf "RLNRE:CELL=%s,CELLR=%s;\n.asyncmsgwait waitfor rpr\n",$1,$2}}'
# NEW: this code delete only the external utran relations
grep -v "^[ ]*$" $RelsPath | grep -v "^[ ]*$" | grep -v "^[ ]*#" | grep ",cellrtype=$RelationType," |
    cut -d , -f 4,6 | sed "s/CELL=//g" | sed "s/CELLR=//g" |
    awk -F , '{printf "RLNRE:CELL=%s,CELLR=%s;\n.asyncmsgwait waitfor rpr\n",$1,$2}'
echo ""
echo ".asyncmsgwait ensurestopped"
