#!/bin/bash

#version="$Id: $"

# ___ Help _____________________________________________________________________

if [ $# -ne 2 ]
then
    This=`echo $0 | sed "s/^.*\///g"`
cat<<__END_OF_HELP__
Usage: $This <BSCCellsFile> <BSCRelsFile>

where
 BSCCellsFile
    The CSV file with the list of internal GSM cells, external GSM cells and
    external UTRAN cells defined in the BSC node.
    This cells file must be generated by list_BSC_cells.sh script. For file
    format informations see that.
 BSCRelsFile
    The CSV file of orignal list of relations in a BSC NE between internal GSM
    and internal/external GSM or external UTRAN cells.
    This relations file must be generated by list_BSC_rels.sh script. For file
    format informations see that.

Example:
 $This BSC01.BSCCells BSC01.BSCRels.tmp

DESCRIPTION:
 For every relation finds the related cell type and set it with a new
 'cellrtype' field. The value is depends on the type of related cell:
  - 'INT': internal GSM cell
  - 'EXT': exteranl GSM cell
  - 'UTRAN': external UTRAN cell

__END_OF_HELP__
exit 1
fi


# ___ Environment ______________________________________________________________

# Temporary directory where you have write permission
if [ "x" == "x$TmpBaseDir" ]
then
    TmpBaseDir=`pwd`
fi
TmpDir="$TmpBaseDir/`echo $0 | sed "s/^.*\///g"`.`whoami`.tmpdir"

# Get absolute path
Path=`echo $0 | sed "s/[^\/]*$//g"`
if [ "1" == `echo $Path | grep "^/" | wc -l` ]
then
    AbsDir=$Path
else
    AbsDir=`\ls -1 $(pwd)/$0 | sed "s/[^\/]*$//g"`
fi


# ___ Preprocessing ____________________________________________________________

# Delete temporary files
if [ -d "$TmpDir" ]
then
    rm -r -f "$TmpDir"
fi
mkdir -p "$TmpDir"


# ___ Parameters _______________________________________________________________

# Parameters
BSCCellsPath=$1
BSCRelsPath=$2


# ___ Main activity ____________________________________________________________

# List cells with types: celltype CELL
egrep -v "^[ ]*(#.*)?$" $BSCCellsPath | cut -d , -f 4,5 |
    sed "s/celltype=//g" | sed "s/CELL=//g" > $TmpDir/awkcells.tmp

# Add new cellrtype filed to the relations
awk -F , -v cellsPath=$TmpDir/awkcells.tmp \
    '# Preparation
    BEGIN{
        cellType["-"]="-"
        while((getline < cellsPath) > 0) {
            cellType[$2]=$1
        }
    }
    # Process lines
    {
        if(0<NF && "#"!=substr($1,1,1)) {
            cellr     = substr($5, index($5, "=")+1)
            cellrType = cellType[cellr]
            printf "%s",$1
            for(i=2; i<=NF; ++i) {
                if(5==i) printf ",cellrtype=%s",cellrType
                printf ",%s",$i
            }
            printf "\n"
        }
        else {
            print $0
        }
    }' $BSCRelsPath


# ___ Postprocessing ___________________________________________________________

# Delete temporary files
rm -r -f $TmpDir
